### ISSUE TITLE
The `set-output` command is deprecated 

### ISSUE THREAD

**Issue by pokopt** [schemacrawler/SchemaCrawler-Action#2]
Hi there and thank for sc-a development. 
I'm facing this warning with current release.
``The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/``
Do you have som plan to update sc-a to use Environment files?
Thanks in advance.
/Peter

**Comment by sualeh** [comment]
@pokopt - thanks. This will be fixed in the next release.
